In [2]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass

np.set_printoptions(precision=2)

In [23]:
@dataclass
class House:
    size: int
    bedrooms: int
    floors: int
    age: int
    price: int

def get_house_features(houses: list) -> np.array:
    # Extract features for each house and return as a NumPy array
    return np.array(
        [[house.size, house.bedrooms, house.floors, house.age] for house in houses]
    )

def get_house_targets(houses: list) -> np.array:
    # Extract targets (prices) for each house and return as a NumPy array
    return np.array([house.price for house in houses])


house_1 = House(size=2104, bedrooms=5, floors=1, age=45, price=460)
house_2 = House(size=1416, bedrooms=3, floors=2, age=40, price=232)
house_3 = House(size=852, bedrooms=2, floors=1, age=35, price=178)
houses = [house_1, house_2, house_3]

X_training_data = get_house_features(houses)
y_training_targets = get_house_targets(houses)

print(f"X_training_data:\n{X_training_data}\n")
print(f"y_training_targets:\n{y_training_targets}\n")

X_training_data:
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]

y_training_targets:
[460 232 178]



In [24]:
bias_init = 785.1811367994083

weight_init_size = 0.39133535
weight_init_bedrooms = 18.75376741
weight_init_floors = -53.36032453
weight_init_age = -26.42131618

weights_init = np.array(
    [weight_init_size, weight_init_bedrooms, weight_init_floors, weight_init_age]
)
print(f"w_init shape: {weights_init.shape}, b_init type: {type(bias_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [20]:
def predict_single_loop(x_house, w_weight, b_bias):
    """
    single predict using linear regression

    Args:
      x (ndarray): Shape (n,) example with multiple features
      w (ndarray): Shape (n,) model parameters
      b (scalar):  model parameter

    Returns:
      p (scalar):  prediction
    """
    n_features = x_house.shape[0]
    p_prediction = 0
    for i in range(n_features):
        p_i_prediction_feature = x_house[i] * w_weight[i]
        p_prediction = p_prediction + p_i_prediction_feature
    p_prediction = p_prediction + b_bias
    return p_prediction

In [25]:
# get a row from our training data
x_vector_house = X_training_data[0]
print(
    f"x_vector_house shape {x_vector_house.shape}, x_vector_house value: {x_vector_house}"
)

# make a prediction
f_wb_prediction = predict_single_loop(x_vector_house, weights_init, bias_init)
print(f"f_wb_prediction shape {f_wb_prediction.shape}, prediction: {f_wb_prediction}")

x_vector_house shape (4,), x_vector_house value: [2104    5    1   45]
f_wb_prediction shape (), prediction: 459.9999976194083
